import { expect, test } from "@playwright/test";
import { createServer, type Server } from "node:http";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  bufferByteSource,
  fileByteSource,
  hasInspectableExtension,
  inspectLocalVideoFile,
  inspectMedia,
  MEDIA_PROBE_CACHE_BYTES,
  MEDIA_PROBE_MAX_CHUNK_BYTES,
  MEDIA_PROBE_MAX_RANGE_REQUESTS,
  MEDIA_PROBE_MAX_TOTAL_BYTES,
  type MediaByteSource,
  type SliceableFile,
} from "@/lib/match-video/media-inspection";
import { MATCH_VIDEO_MAX_BYTES } from "@/lib/match-video/limits";

/**
 * The attachment's duration is the one number the whole feature rests on: it
 * decides whether the recording covers the match and it bounds every seek the
 * match room performs. A wrong duration does not look broken — playback simply
 * lands somewhere else — so it is parsed from the container here, from the
 * VIDEO track, and never taken from a client or from an audio stream.
 *
 * The other half of this spec is that the parse stays bounded. The input is a
 * file a stranger chose; a crafted container can ask a parser to read forever.
 * The virtual-source tests below run the inspector against files that claim to
 * be gigabytes without a byte of that ever existing.
 *
 * Fixtures are generated by `tests/fixtures/match-video/generate.mjs` — owned,
 * synthesised, tiny. Read its header before changing them.
 */

const FIXTURES = resolve("tests/fixtures/match-video");

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(resolve(FIXTURES, name)));
}

/** Every generated clip is exactly sixty frames at 30 fps. */
const FIXTURE_DURATION_SECONDS = 2;

/* -------------------------------------------------------------------------
 * Test doubles
 * ---------------------------------------------------------------------- */

interface RecordedRead {
  start: number;
  end: number;
}

/** A byte source that records every read it is asked to perform. */
function recordingSource(
  bytes: Uint8Array,
): MediaByteSource & { reads: RecordedRead[] } {
  const reads: RecordedRead[] = [];
  return {
    reads,
    byteLength: bytes.byteLength,
    async read(start, end) {
      reads.push({ start, end });
      return bytes.subarray(start, end);
    },
  };
}

/** The minimum of `File` the inspector may touch, with slicing recorded. */
type FakeFile = SliceableFile & {
  slices: RecordedRead[];
  wholeFileReads: number;
  arrayBuffer(): Promise<ArrayBuffer>;
};

function fakeFile(name: string, bytes: Uint8Array): FakeFile {
  const slices: RecordedRead[] = [];
  return {
    name,
    size: bytes.byteLength,
    type: "video/mp4",
    slices,
    wholeFileReads: 0,
    slice(start: number, end: number) {
      slices.push({ start, end });
      return {
        async arrayBuffer() {
          const copy = bytes.slice(start, end);
          return copy.buffer.slice(
            copy.byteOffset,
            copy.byteOffset + copy.byteLength,
          ) as ArrayBuffer;
        },
      };
    },
    /** A `File` has this. Touching it is the bug these tests exist to catch. */
    async arrayBuffer() {
      this.wholeFileReads += 1;
      return bytes.buffer as ArrayBuffer;
    },
  };
}

/* -------------------------------------------------------------------------
 * ISO-BMFF box walking, used to build the virtual large file
 * ---------------------------------------------------------------------- */

interface Box {
  type: string;
  start: number;
  size: number;
}

/** Top-level boxes only. Enough to find `moov` and `mdat`. */
function topLevelBoxes(bytes: Uint8Array): Box[] {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const boxes: Box[] = [];
  let at = 0;
  while (at + 8 <= bytes.byteLength) {
    const size = view.getUint32(at);
    const type = String.fromCharCode(...bytes.subarray(at + 4, at + 8));
    if (size < 8) break;
    boxes.push({ type, start: at, size });
    at += size;
  }
  return boxes;
}

/* -------------------------------------------------------------------------
 * Supported containers
 * ---------------------------------------------------------------------- */

const CONTAINERS: {
  file: string;
  format: string;
  codec: string;
}[] = [
  { file: "h264-faststart.mp4", format: "MP4", codec: "avc" },
  { file: "h264-tail.mp4", format: "MP4", codec: "avc" },
  { file: "h264.mov", format: "QuickTime File Format", codec: "avc" },
  { file: "vp9.webm", format: "WebM", codec: "vp9" },
  { file: "vp9.mkv", format: "Matroska", codec: "vp9" },
];

for (const container of CONTAINERS) {
  test(`${container.file} reports its video track's media end`, async () => {
    const result = await inspectMedia(
      bufferByteSource(fixture(container.file)),
    );
    if (!result.ok) throw new Error(`refused: ${result.error.detail}`);

    expect(result.value.formatName).toBe(container.format);
    expect(result.value.videoCodec).toBe(container.codec);
    expect(result.value.codedWidth).toBe(64);
    expect(result.value.codedHeight).toBe(64);
    expect(result.value.durationSeconds).toBeCloseTo(
      FIXTURE_DURATION_SECONDS,
      2,
    );
  });
}

test("metadata at the end of the file is still found", async () => {
  // The fixture only proves anything if its `moov` really is last: a parser
  // that reads the head of the file and stops would pass on the other MP4.
  const boxes = topLevelBoxes(fixture("h264-tail.mp4"));
  expect(boxes.at(-1)?.type).toBe("moov");
  expect(topLevelBoxes(fixture("h264-faststart.mp4"))[1]?.type).toBe("moov");

  const tail = await inspectMedia(bufferByteSource(fixture("h264-tail.mp4")));
  const head = await inspectMedia(
    bufferByteSource(fixture("h264-faststart.mp4")),
  );
  expect(tail.ok && head.ok).toBe(true);
  if (!tail.ok || !head.ok) return;
  expect(tail.value.durationSeconds).toBeCloseTo(head.value.durationSeconds, 6);
});

/* -------------------------------------------------------------------------
 * Refusals
 * ---------------------------------------------------------------------- */

test("an audio-only file has no duration to report", async () => {
  const result = await inspectMedia(
    bufferByteSource(fixture("audio-only.webm")),
  );
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.error.code).toBe("unsupported_media");
  expect(result.error.detail).toBe("no_video_track");
  // The audio runs for two seconds. Trusting it would have invented a duration.
  expect(result.error.message).toContain("MP4");
});

test("a truncated file is refused, not half-read", async () => {
  // The tail fixture keeps its `moov` last, so a cut-short file is a file with
  // no metadata at all — which is what an interrupted upload actually leaves.
  const whole = fixture("h264-tail.mp4");
  const result = await inspectMedia(
    bufferByteSource(whole.subarray(0, Math.floor(whole.byteLength / 3))),
  );
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("unsupported_media");
});

test("a corrupted metadata region is refused", async () => {
  const bytes = fixture("h264-faststart.mp4").slice();
  const moov = topLevelBoxes(bytes).find((box) => box.type === "moov");
  if (!moov) throw new Error("fixture layout changed");
  for (let at = moov.start + 8; at < moov.start + moov.size; at++) {
    bytes[at] = (at * 97) % 256;
  }
  const result = await inspectMedia(bufferByteSource(bytes));
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("unsupported_media");
});

test("a file of noise is refused", async () => {
  const noise = new Uint8Array(4096);
  for (let i = 0; i < noise.length; i++) noise[i] = (i * 37 + 11) % 256;
  const result = await inspectMedia(bufferByteSource(noise));
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("unsupported_media");
});

test("AVI is refused by content as well as by extension", async () => {
  // A real RIFF/AVI header. The pinned Mediabunny build ships no AVI reader, so
  // renaming the file to .mp4 must not get it any further than keeping .avi.
  const avi = new Uint8Array(2048);
  avi.set([0x52, 0x49, 0x46, 0x46], 0); // "RIFF"
  new DataView(avi.buffer).setUint32(4, avi.byteLength - 8, true);
  avi.set([0x41, 0x56, 0x49, 0x20], 8); // "AVI "
  avi.set([0x4c, 0x49, 0x53, 0x54], 12); // "LIST"

  const result = await inspectMedia(bufferByteSource(avi));
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("unsupported_media");

  expect(hasInspectableExtension("match.avi")).toBe(false);
  const byName = await inspectLocalVideoFile(fakeFile("match.avi", avi));
  expect(byName.ok).toBe(false);
  if (!byName.ok) expect(byName.error.detail).toBe("extension_not_supported");
});

test("an HLS manifest is never followed", async () => {
  // HLS is excluded from the format list on purpose: parsing a manifest would
  // make the server fetch URLs the uploader chose.
  const manifest = new TextEncoder().encode(
    "#EXTM3U\n#EXT-X-VERSION:3\n#EXTINF:4,\nhttps://example.invalid/0.ts\n",
  );
  const result = await inspectMedia(bufferByteSource(manifest));
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("unsupported_media");
});

test("an empty or oversized source never reaches the parser", async () => {
  const empty = recordingSource(new Uint8Array(0));
  const emptyResult = await inspectMedia(empty);
  expect(emptyResult.ok).toBe(false);
  if (!emptyResult.ok) expect(emptyResult.error.code).toBe("empty_file");
  expect(empty.reads).toHaveLength(0);

  const huge: MediaByteSource = {
    byteLength: MATCH_VIDEO_MAX_BYTES + 1,
    async read() {
      throw new Error("must not read");
    },
  };
  const hugeResult = await inspectMedia(huge);
  expect(hugeResult.ok).toBe(false);
  if (!hugeResult.ok) expect(hugeResult.error.code).toBe("file_too_large");
});

/* -------------------------------------------------------------------------
 * Local preflight
 * ---------------------------------------------------------------------- */

test("local preflight slices the file instead of buffering it", async () => {
  const bytes = fixture("h264-faststart.mp4");
  const file = fakeFile("match.mp4", bytes);

  const result = await inspectLocalVideoFile(file);
  expect(result.ok).toBe(true);
  if (result.ok) {
    expect(result.value.durationSeconds).toBeCloseTo(
      FIXTURE_DURATION_SECONDS,
      2,
    );
  }

  expect(file.slices.length).toBeGreaterThan(0);
  expect(file.wholeFileReads).toBe(0);
  for (const slice of file.slices) {
    expect(slice.end - slice.start).toBeLessThanOrEqual(
      MEDIA_PROBE_MAX_CHUNK_BYTES,
    );
  }
});

test("fileByteSource reads only the window it was asked for", async () => {
  const bytes = fixture("h264-faststart.mp4");
  const file = fakeFile("match.mp4", bytes);
  const source = fileByteSource(file);

  const window = await source.read(100, 180, new AbortController().signal);
  expect(Array.from(window)).toEqual(Array.from(bytes.subarray(100, 180)));
  expect(file.slices).toEqual([{ start: 100, end: 180 }]);
  expect(file.wholeFileReads).toBe(0);
});

/* -------------------------------------------------------------------------
 * Bounded reads over virtual large sources
 * ---------------------------------------------------------------------- */

/**
 * A multi-gigabyte MP4 that does not exist.
 *
 * The real tail-metadata fixture's `mdat` is inflated to `paddingBytes`, so the
 * file claims to be about 3 GiB while only its header and its trailing `moov`
 * are ever materialised. Everything between them reads as zeros — which is
 * exactly what a parser that respects the sample table never asks for.
 */
function virtualLargeMp4(paddingBytes: number): MediaByteSource & {
  reads: RecordedRead[];
} {
  const real = fixture("h264-tail.mp4");
  const boxes = topLevelBoxes(real);
  const mdat = boxes.find((box) => box.type === "mdat");
  const moov = boxes.find((box) => box.type === "moov");
  if (!mdat || !moov) throw new Error("fixture layout changed");

  const head = real.slice(0, mdat.start + mdat.size);
  new DataView(head.buffer).setUint32(mdat.start, mdat.size + paddingBytes);
  const tail = real.slice(moov.start);

  const padStart = mdat.start + mdat.size;
  const padEnd = padStart + paddingBytes;
  const reads: RecordedRead[] = [];

  return {
    reads,
    byteLength: padEnd + tail.byteLength,
    prefetchProfile: "network",
    async read(start, end) {
      reads.push({ start, end });
      const out = new Uint8Array(end - start);
      for (let at = start; at < end; at++) {
        if (at < padStart) out[at - start] = head[at];
        else if (at >= padEnd) out[at - start] = tail[at - padEnd];
      }
      return out;
    },
  };
}

test("a 3 GiB file is inspected without reading 3 GiB", async () => {
  const source = virtualLargeMp4(3 * 1024 * 1024 * 1024);
  const result = await inspectMedia(source);

  if (!result.ok) throw new Error(`refused: ${result.error.detail}`);
  expect(result.value.durationSeconds).toBeCloseTo(FIXTURE_DURATION_SECONDS, 2);

  expect(result.value.bytesRead).toBeLessThan(MEDIA_PROBE_MAX_TOTAL_BYTES);
  expect(result.value.rangeRequests).toBeLessThanOrEqual(
    MEDIA_PROBE_MAX_RANGE_REQUESTS,
  );
  // The whole point: a fraction of a megabyte for a file of gigabytes.
  expect(result.value.bytesRead).toBeLessThan(1024 * 1024);
  for (const read of source.reads) {
    expect(read.end - read.start).toBeLessThanOrEqual(
      MEDIA_PROBE_MAX_CHUNK_BYTES,
    );
  }
});

/**
 * Bytes the source was asked for a second time after already supplying them.
 *
 * Re-read amplification is the thing the cache budget exists to bound, and it
 * is invisible in `bytesRead` alone: a file read twice and a file twice as
 * large cost the same total. Counting the overlap separates them.
 */
function refetchedBytes(reads: RecordedRead[]): number {
  const seen: RecordedRead[] = []; // kept disjoint and sorted
  let repeated = 0;
  for (const read of reads) {
    for (const span of seen) {
      const start = Math.max(read.start, span.start);
      const end = Math.min(read.end, span.end);
      if (end > start) repeated += end - start;
    }
    seen.push({ ...read });
    seen.sort((a, b) => a.start - b.start);
    for (let i = 1; i < seen.length;) {
      if (seen[i].start <= seen[i - 1].end) {
        seen[i - 1].end = Math.max(seen[i - 1].end, seen[i].end);
        seen.splice(i, 1);
      } else {
        i++;
      }
    }
  }
  return repeated;
}

test("the cache budget is what keeps a revisited region from being refetched", async () => {
  // This file is read out of order by construction: the parser takes the head,
  // jumps three gigabytes to the trailing `moov`, and then walks that metadata
  // repeatedly for the duration, the first timestamp and the codec. Whether
  // those revisits cost the source anything is decided by one number — the
  // cache size `inspectMedia` hands Mediabunny — so running the same parse at
  // the production budget and with the cache disabled is what proves the
  // number governs rather than merely being declared.
  const padding = 3 * 1024 * 1024 * 1024;

  const bounded = virtualLargeMp4(padding);
  const withCache = await inspectMedia(bounded);
  if (!withCache.ok) throw new Error(`refused: ${withCache.error.detail}`);

  const unbounded = virtualLargeMp4(padding);
  const withoutCache = await inspectMedia(unbounded, { cacheBytes: 0 });
  if (!withoutCache.ok)
    throw new Error(`refused: ${withoutCache.error.detail}`);

  // Same file, same answer: amplification is the only difference between them.
  expect(withoutCache.value.durationSeconds).toBeCloseTo(
    withCache.value.durationSeconds,
    6,
  );

  // At the production budget every byte is fetched once, and the reason is the
  // budget: the whole working set fits inside it with room to spare.
  expect(refetchedBytes(bounded.reads)).toBe(0);
  expect(withCache.value.bytesRead).toBeLessThanOrEqual(
    MEDIA_PROBE_CACHE_BYTES,
  );

  // Take the cache away and the same parse pulls the same regions again.
  expect(refetchedBytes(unbounded.reads)).toBeGreaterThan(0);
  expect(withoutCache.value.bytesRead).toBeGreaterThan(
    withCache.value.bytesRead,
  );
  expect(unbounded.reads.length).toBeGreaterThan(bounded.reads.length);
});

test("an oversized metadata region trips the byte budget", async () => {
  // A `moov` that claims 64 MiB. Structurally legal, twice the budget, and the
  // shape a hostile file uses to make a parser allocate.
  const real = fixture("h264-faststart.mp4");
  const boxes = topLevelBoxes(real);
  const moov = boxes.find((box) => box.type === "moov");
  if (!moov) throw new Error("fixture layout changed");

  const claimed = 64 * 1024 * 1024;
  const head = real.slice(0, moov.start + moov.size);
  new DataView(head.buffer).setUint32(moov.start, claimed);
  const reads: RecordedRead[] = [];
  const source: MediaByteSource = {
    byteLength: moov.start + claimed,
    async read(start, end) {
      reads.push({ start, end });
      const out = new Uint8Array(end - start);
      for (let at = start; at < end && at < head.byteLength; at++) {
        out[at - start] = head[at];
      }
      return out;
    },
  };

  const result = await inspectMedia(source);
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.error.code).toBe("media_probe_budget");
  expect(result.error.detail).toBe("total_bytes_limit");
  // The guidance a structural refusal gives is the MP4 export, not "try again".
  expect(result.error.message).toContain("Export it as an MP4");

  const total = reads.reduce((sum, read) => sum + (read.end - read.start), 0);
  expect(total).toBeLessThanOrEqual(MEDIA_PROBE_MAX_TOTAL_BYTES);
  expect(reads.length).toBeLessThanOrEqual(MEDIA_PROBE_MAX_RANGE_REQUESTS);
});

test("a box chain that never ends trips the request budget", async () => {
  // Thousands of tiny top-level boxes ahead of the metadata. Every byte is
  // legal and the file is small, so no size or byte limit catches it — only
  // counting the reads does. Without that counter this walks forever.
  const real = fixture("h264-faststart.mp4");
  const ftypSize = topLevelBoxes(real)[0].size;
  const fillerCount = 2000;
  const filler = new Uint8Array(fillerCount * 16);
  const fillerView = new DataView(filler.buffer);
  for (let i = 0; i < fillerCount; i++) {
    fillerView.setUint32(i * 16, 16);
    filler.set([0x66, 0x72, 0x65, 0x65], i * 16 + 4); // "free"
  }
  const padded = new Uint8Array(real.byteLength + filler.byteLength);
  padded.set(real.subarray(0, ftypSize), 0);
  padded.set(filler, ftypSize);
  padded.set(real.subarray(ftypSize), ftypSize + filler.byteLength);

  let reads = 0;
  const source: MediaByteSource = {
    byteLength: padded.byteLength,
    async read(start, end) {
      reads += 1;
      return padded.subarray(start, end);
    },
  };

  const result = await inspectMedia(source);
  expect(result.ok).toBe(false);
  if (!result.ok) {
    expect(result.error.code).toBe("media_probe_budget");
    expect(result.error.detail).toBe("range_request_limit");
  }
  expect(reads).toBe(MEDIA_PROBE_MAX_RANGE_REQUESTS);
});

test("the deadline ends a parse that will not finish", async () => {
  let aborted = false;
  const source: MediaByteSource = {
    byteLength: fixture("h264-faststart.mp4").byteLength,
    read(_start, _end, signal) {
      return new Promise((_resolve, reject) => {
        signal.addEventListener("abort", () => {
          aborted = true;
          reject(new Error("aborted"));
        });
      });
    },
  };

  const started = Date.now();
  const result = await inspectMedia(source, { deadlineMs: 250 });
  expect(Date.now() - started).toBeLessThan(5000);
  expect(aborted).toBe(true);
  expect(result.ok).toBe(false);
  if (!result.ok) {
    expect(result.error.code).toBe("media_probe_budget");
    expect(result.error.detail).toBe("deadline_exceeded");
  }
});

test("a failing byte source stays retryable", async () => {
  // Nothing was learned about the file, so this must not tell the user to
  // re-export their video — it must tell them to try again.
  const source: MediaByteSource = {
    byteLength: 1024,
    async read() {
      throw new Error("ECONNRESET");
    },
  };
  const result = await inspectMedia(source);
  expect(result.ok).toBe(false);
  if (!result.ok) {
    expect(result.error.code).toBe("storage_unavailable");
    expect(result.error.detail).toBe("read_failed");
  }
});

test("disposal runs on every exit", async () => {
  let disposals = 0;
  const bytes = fixture("h264-faststart.mp4");
  const make = (ok: boolean): MediaByteSource => ({
    byteLength: bytes.byteLength,
    async read(start, end) {
      if (!ok) throw new Error("boom");
      return bytes.subarray(start, end);
    },
    dispose() {
      disposals += 1;
    },
  });

  expect((await inspectMedia(make(true))).ok).toBe(true);
  expect((await inspectMedia(make(false))).ok).toBe(false);
  expect(disposals).toBe(2);
});

/* -------------------------------------------------------------------------
 * Parsed clock vs. the browser's
 * ---------------------------------------------------------------------- */

/**
 * The parsed duration is only useful if it is the same number `<video>` will
 * report, because the match room seeks a real element. Chromium plays the MP4
 * and WebM fixtures; it has no demuxer for Matroska or QuickTime, so those two
 * are verified by parse alone above rather than by pretending the check ran.
 */
const PLAYABLE: { file: string; mime: string }[] = [
  { file: "h264-faststart.mp4", mime: "video/mp4" },
  { file: "h264-tail.mp4", mime: "video/mp4" },
  { file: "vp9.webm", mime: "video/webm" },
];

test.describe("parsed clocks agree with the browser", () => {
  let server: Server;
  let origin: string;

  test.beforeAll(async () => {
    // Range support is not decoration: without `Accept-Ranges`, Chromium
    // reports an empty seekable range and every seek silently clamps to zero,
    // which is also how playback behaves against real blob storage.
    server = createServer((request, response) => {
      const name = (request.url ?? "/").slice(1);
      const entry = PLAYABLE.find((item) => item.file === name);
      if (!entry) {
        response.writeHead(200, { "content-type": "text/html" });
        response.end("<!doctype html><title>probe</title>");
        return;
      }
      const bytes = Buffer.from(fixture(entry.file));
      const range = /bytes=(\d*)-(\d*)/.exec(request.headers.range ?? "");
      if (range) {
        const start = Number(range[1] || 0);
        const end = range[2] ? Number(range[2]) : bytes.byteLength - 1;
        response.writeHead(206, {
          "content-type": entry.mime,
          "accept-ranges": "bytes",
          "content-range": `bytes ${start}-${end}/${bytes.byteLength}`,
          "content-length": String(end - start + 1),
        });
        response.end(bytes.subarray(start, end + 1));
        return;
      }
      response.writeHead(200, {
        "content-type": entry.mime,
        "accept-ranges": "bytes",
        "content-length": String(bytes.byteLength),
      });
      response.end(bytes);
    });
    await new Promise<void>((done) => server.listen(0, "127.0.0.1", done));
    const address = server.address();
    if (!address || typeof address === "string") throw new Error("no port");
    origin = `http://127.0.0.1:${address.port}`;
  });

  test.afterAll(() => {
    server.close();
  });

  for (const entry of PLAYABLE) {
    test(`${entry.file} plays to the duration we parsed`, async ({ page }) => {
      const parsed = await inspectMedia(bufferByteSource(fixture(entry.file)));
      if (!parsed.ok) throw new Error(`refused: ${parsed.error.detail}`);

      await page.goto(`${origin}/blank`);
      const observed = await page.evaluate(async (url: string) => {
        const video = document.createElement("video");
        document.body.append(video);
        video.muted = true;
        video.preload = "auto";
        video.src = url;
        await new Promise((done, fail) => {
          video.oncanplaythrough = done;
          video.onerror = () => fail(new Error("load failed"));
        });
        const duration = video.duration;
        const seekableEnd = video.seekable.length ? video.seekable.end(0) : 0;

        // A seek near the end must land near the end. If the parsed clock and
        // the element's clock disagreed, this is where it would show.
        const target = Math.max(0, duration - 0.25);
        await new Promise((done, fail) => {
          video.onseeked = done;
          video.onerror = () => fail(new Error("seek failed"));
          video.currentTime = target;
        });
        return { duration, seekableEnd, target, landed: video.currentTime };
      }, `${origin}/${entry.file}`);

      expect(observed.duration).toBeCloseTo(parsed.value.durationSeconds, 1);
      expect(observed.seekableEnd).toBeCloseTo(parsed.value.durationSeconds, 1);
      expect(observed.landed).toBeCloseTo(observed.target, 2);
    });
  }
});
